service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    CLIENT_ID: 851259002038-l4jguinr6f2e5kh2uha9lmder3dqjnuo.apps.googleusercontent.com
    CLIENT_SECRET: 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
    CALENDAR_ID: fullstackwebdev@careerfoundry.com

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get